# Generated by Django 2.2.2 on 2019-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_invoice',
            field=models.CharField(max_length=100),
        ),
    ]
