# Generated by Django 2.2.2 on 2019-06-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190611_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='customer_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='invoice.Invoice'),
            preserve_default=False,
        ),
    ]
