# Generated by Django 2.2.2 on 2019-06-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoicedetail_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='customer_name',
            new_name='customer_id',
        ),
    ]
