# Generated by Django 2.2.2 on 2019-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20190612_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_invoice',
            field=models.IntegerField(max_length=100),
        ),
    ]
