# Generated by Django 2.2.2 on 2019-06-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20190612_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_invoice',
            field=models.IntegerField(),
        ),
    ]
